export interface iPaties{
    shipper_code: string,
    shipper_name: string,
    shipper_address: string,
    shipper_email: string,
    consignee_code: string,
    consignee_name: string,
    consignee_address: string,
    consignee_email: string,
    actual_consignee_code: string,
    actual_consignee_name: string,
    actual_consignee_address: string,
    billto_code: string,
    billto_name: string,
    billto_address: string,
    notifypart1_name: string,
    notifypart1_address: string,
    notifypart2_name: string,
    notifypart2_address: string,
}