import { Component, OnInit } from "@angular/core";

export interface PkgType {
  value: string;
  viewValue: string;
}
export interface iCargoedit{
  container: string;
  package_goods: string;
  gw_vol: string;
}
@Component({
  selector: 'app-inbound-sea-freight-do-cargo-edit',
  templateUrl: './inbound-sea-freight-do-cargo-edit.component.html',
  styleUrls: ['./inbound-sea-freight-do-cargo-edit.component.css']
})
export class InboundSeaFreightDoCargoEditComponent implements OnInit {
  selectedvol = 'Cbm';
  selected = 'Kgs';
  selectedValue: string;
  displayedColumns = ['container','package_goods','gw_vol'];
  dataSource = ELEMENT_DATA;

  pkgtype: PkgType[] = [
    {value:'undefined',viewValue:'undefined'},
    {value:'', viewValue:'AEROSOL'},
    {value:'', viewValue:'ALUMINIUM DRUM'},
    {value:'', viewValue:'ALUMINIUM DRUM'}, 
    {value:'', viewValue:'REMOVABLE HEAD'},
    {value:'', viewValue:'AMPOULE, NON-PROTECTED'},
    {value:'', viewValue:'AMPOULE, PROTECTED'},
    {value:'', viewValue:'ATOMIZER'},
    {value:'', viewValue:'BAG'},
    {value:'', viewValue:'BAG, FLEXIBLE CONTAINER'},
    {value:'', viewValue:'BAG, SUPER BULK'},
    {value:'', viewValue:'BAG, WOVEN PLASTIC, SIFT PROOF'},
    {value:'', viewValue:'BAGS'},
    {value:'', viewValue:'BALE'},
    {value:'', viewValue:'BALE, NON-COMPRESSED'},
    {value:'', viewValue:'BALLOON, NON-PROTECTED'},
    {value:'', viewValue:'BALLOON, PROTECTED'},
    {value:'', viewValue:'BAR'},
    {value:'', viewValue:'BARREL'},
    {value:'', viewValue:'BARREL, WOODEN'},
    {value:'', viewValue:'BARREL, WOODEN, BUNG TYPE'},
    {value:'', viewValue:'BARREL, WOODEN, REMOVABLE HEAD'},
    {value:'', viewValue:'BARS, IN BUNDLE/BUNCH/TRUSS'},
    {value:'', viewValue:'BASIN'},
    {value:'', viewValue:'BASKET'},
    {value:'', viewValue:'BASKET, WITH HANDLE, CARDBOARD'},
    {value:'', viewValue:'BASKET, WITH HANDLE, PLASTIC'},
    {value:'', viewValue:'BEER CRATE'},
    {value:'', viewValue:'BIN'},
    {value:'', viewValue:'BLOCK'},
    {value:'', viewValue:'BOARD'},
    {value:'', viewValue:'BOBBIN'},
    {value:'', viewValue:'BOLT'},
    {value:'', viewValue:'BOTTLE'},
    {value:'', viewValue:'BOTTLE, GAS'},
    {value:'', viewValue:'BOTTLE, NON-PROTECTED, CYLINDRICAL'},
    {value:'', viewValue:'BOTTLE, PROTECTED BULBOUS'},
    {value:'', viewValue:'BOTTLE, PROTECTED CYLINDRICAL'},
    {value:'', viewValue:'BOTTLECRATE / BOTTLERACK'},
    {value:'', viewValue:'BOX'},
    {value:'', viewValue:'BOX, ALUMINIUM'},
    {value:'', viewValue:'BOX, COMMONWEALTH HANDLING EQUIPMENT POOL (CHEP), EUROBOX'},
    {value:'', viewValue:'BOX, FIBREBOARD'},
    {value:'', viewValue:'BOX, FOR LIQUIDS'},
    {value:'', viewValue:'BOX, NATURAL WOOD'},
    {value:'', viewValue:'BOX, PLASTIC, EXPANDED'},
    {value:'', viewValue:'BOX, PLASTIC, SOLID'},
    {value:'', viewValue:'BOX, PLYWOOD'},
    {value:'', viewValue:'BOX, RECONSTITUTED WOOD'},
    {value:'', viewValue: 'BOX, STEEL'},
    {value:'', viewValue:'BOX, WOODEN, NATURAL WOOD, WITH SIFT PROOF WALLS'},
    {value:'', viewValue:'BUCKET'},
    {value:'', viewValue:'BULK, GAS (AT 1031 MBAR AND 15°C)'},
    {value:'', viewValue:'BULK, LIQUEFIED GAS (AT ABNORMAL TEMPERATURE/PRESSURE)'},
    {value:'', viewValue:'BULK, LIQUID'},
    {value:'', viewValue:'BULK, SOLID, FINE PARTICLES (“POWDERS”)'},
    {value:'', viewValue:'BULK, SOLID, GRANULAR PARTICLES (“GRAINS”)'},
    {value:'', viewValue:'BULK, SOLID, LARGE PARTICLES (“NODULES”)'},
    {value:'', viewValue:'BUNCH'},
    {value:'', viewValue:'BUNDLE'},
    {value:'', viewValue:'BUTT'},
    {value:'', viewValue:'CAGE'},
    {value:'', viewValue:'CAGE, COMMONWEALTH HANDLING EQUIPMENT POOL (CHEP)'},
    {value:'', viewValue:'CAGE, ROLL'},
    {value:'', viewValue:'CAN'},
    {value:'', viewValue:'CAN, CYLINDRICAL'},
    {value:'', viewValue:'CAN, RECTANGULAR'},
    {value:'', viewValue:'CANISTER'},
    {value:'', viewValue:'CANVAS'},
    {value:'', viewValue:'CAPSULE'},
    {value:'', viewValue:'CARBOARD PACKAGE'},
    {value:'', viewValue:'CARBOY, NON-PROTECTED'},
    {value:'', viewValue:'CARBOY, PROTECTED'},
    {value:'', viewValue:'CARD'},
    {value:'', viewValue:'CARDBOARD TRAY'},
    {value:'', viewValue:'CARDBOARD CASE, WITH PALLET BASE'},
    {value:'', viewValue:'CARDBOARD CRATE'},
    {value:'', viewValue:'CART, FLATBED'},
    {value:'', viewValue:'CARTONS'},
    {value:'', viewValue:'CARTRIDGE'},
    {value:'', viewValue:'CASE'},
    {value:'', viewValue:'CASE (STEEL)'},
    {value:'', viewValue:'CASE, ISOTHERMIC'},
    {value:'', viewValue:'CASE, SKELETON'},
    {value:'', viewValue:'CASE, WITH PALLET BASE'},
    {value:'', viewValue:'CASK'},
    {value:'', viewValue:'CHEST'},
    {value:'', viewValue:'CHURN'},
    {value:'', viewValue:'CLAMSHELL'},
    {value:'', viewValue:'COFFER'},
    {value:'', viewValue:'COFFIN'},
    {value:'', viewValue:'COIL'},
    {value:'', viewValue:'COMPOSITE PACKAGING, GLASS RECEPTACLE'},
    {value:'', viewValue:'COMPOSITE PACKAGING, GLASS RECEPTACLE IN ALUMINIUM CRATE'},
    {value:'', viewValue:'COMPOSITE PACKAGING, GLASS RECEPTACLE IN ALUMINIUM DRUM'},
    {value:'', viewValue:'COMPOSITE PACKAGING, GLASS RECEPTACLE IN EXPANDABLE PLASTIC PACK'},
    {value:'', viewValue:'COMPOSITE PACKAGING, GLASS RECEPTACLE IN FIBRE DRUM'},
    {value:'', viewValue:'COMPOSITE PACKAGING, GLASS RECEPTACLE IN FIBREBOARD BOX'},
    {value:'', viewValue:'COMPOSITE PACKAGING, GLASS RECEPTACLE IN SOLID PLASTIC PACK'},
    {value:'', viewValue:'COMPOSITE PACKAGING, GLASS RECEPTACLE IN STEEL CRATE BOX'},
    {value:'', viewValue:'COMPOSITE PACKAGING, GLASS RECEPTACLE IN STEEL DRUM'},
    {value:'', viewValue:'COMPOSITE PACKAGING, GLASS RECEPTACLE IN WICKERWORK HAMPER'},
    {value:'', viewValue:'COMPOSITE PACKAGING, GLASS RECEPTACLE IN WOODEN BOX'},
    {value:'', viewValue:'COMPOSITE PACKAGING, PLASTIC RECEPTACLE'},
    {value:'', viewValue:'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN ALUMINIUM CRATE'},
    {value:'', viewValue:'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN ALUMINIUM DRUM'},
    {value:'', viewValue:'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN FIBRE DRUM'},
    {value:'', viewValue:'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN FIBREBOARD BOX'},
    {value:'', viewValue:'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN PLASTIC DRUM'},
    {value:'', viewValue:'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN PLYWOOD BOX'},
    {value:'', viewValue:'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN PLYWOOD DRUM'},
    {value:'', viewValue:'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN SOLID PLASTIC BOX'},
    {value:'', viewValue:'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN STEEL CRATE BOX'},
    {value:'', viewValue:'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN STEEL DRUM'},
    {value:'', viewValue:'COMPOSITE PACKAGING, PLASTIC RECEPTACLE IN WOODEN BOX'},
    {value:'', viewValue:'CONE'},
    {value:'', viewValue:'CONTAINER, NOT OTHERWISE SPECIFIED AS TRANSPORT EQUIPMENT'},
    {value:'', viewValue:'COVER'},
    {value:'', viewValue:'CRATE'},
    {value:'', viewValue:'CRATE(S)'},
    {value:'', viewValue:'CRATE, FRUIT'},
    {value:'', viewValue:'CRATE, MILK'},
    {value:'', viewValue:'CRATE, MULTIPLE LAYER, CARDBOARD'},
    {value:'', viewValue:'CRATE, MULTIPLE LAYER, PLASTIC'},
    {value:'', viewValue:'CRATE, MULTIPLE LAYER, WOODEN'},
    {value:'', viewValue:'CRATE, SHALLOW'},
    {value:'', viewValue:'CREEL'},
    {value:'', viewValue:'CTNS'},
    {value:'', viewValue:'CUP'},
    {value:'', viewValue:'CYLINDER'},
    {value:'', viewValue:'DEMIJOHN, NON-PROTECTED'},
    {value:'', viewValue:'DEMIJOHN, PROTECTED'},
    {value:'', viewValue:'DISPENSER'},
    {value:'', viewValue:'DRUM'},
    {value:'', viewValue:'DRUM, ALUMINIUM, NON-REMOVABLE HEAD'},
    {value:'', viewValue:'DRUM, PLASTIC, NON-REMOVABLE HEAD'},
    {value:'', viewValue:'ENVELOPE'},
    {value:'', viewValue:'ENVELOPE (STEEL)'},
    {value:'', viewValue:'FIBRE DRUM'},
    {value:'', viewValue:'FILMPACK'},
    {value:'', viewValue:'FIRKIN'},
    {value:'', viewValue:'FLASK'},
    {value:'', viewValue:'FOODTAINER'},
    {value:'', viewValue:'FOOTLOCKER'},
    {value:'', viewValue:'FRAME'},
    {value:'', viewValue:'GIRDER'},
    {value:'', viewValue:'GIRDERS, IN BUNDLE/BUNCH/TRUSS'},
    {value:'', viewValue:'GLASS RECEPTACLE'},
    {value:'', viewValue:'HAMPER'},
    {value:'', viewValue:'HOGSHEAD'},
    {value:'', viewValue:'INGOT'},
    {value:'', viewValue:'INGOTS, IN BUNDLE/BUNCH/TRUSS'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, ALUMINIUM'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, ALUMINIUM, LIQUID'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, ALUMINIUM, PRESSURISED > 10 KPA'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, COMPOSITE, FLEXIBLE PLASTIC, LIQUIDS'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, COMPOSITE, FLEXIBLE PLASTIC, PRESSURISED'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, COMPOSITE, FLEXIBLE PLASTIC, SOLIDS'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, COMPOSITE, RIGID PLASTIC, PRESSURISED'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, COMPOSITE, RIGID PLASTIC, SOLIDS'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, FIBREBOARD'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, FLEXIBLE'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, METAL'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, METAL, LIQUID'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, METAL, OTHER THAN STEEL'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, METAL, PRESSURE 10 KPA'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, NATURAL WOOD'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, NATURAL WOOD, WITH INNER LINER'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, PAPER, MULTI-WALL'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, PAPER, MULTI-WALL, WATER RESISTANT'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, PLASTIC FILM'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, PLYWOOD'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, PLYWOOD, WITH INNER LINER'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, RECONSTITUTED WOOD'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, RECONSTITUTED WOOD, WITH INNER LINER'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, RIGID PLASTIC'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, RIGID PLASTIC, FREESTANDING, LIQUIDS'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, RIGID PLASTIC, FREESTANDING, PRESSURISED'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, RIGID PLASTIC, FREESTANDING, SOLIDS'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, RIGID PLASTIC, WITH STRUCTURAL EQUIPMENT, LIQUIDS'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, RIGID PLASTIC, WITH STRUCTURAL EQUIPMENT, PRESSURISED'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, RIGID PLASTIC, WITH STRUCTURAL EQUIPMENT, SOLIDS'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, STEEL'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, STEEL, LIQUID'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, STEEL, PRESSURISED > 10 KPA'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, TEXTILE WITH OUT COAT/LINER'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, TEXTILE, COATED'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, TEXTILE, COATED AND LINER'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, TEXTILE, WITH LINER'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, WOVEN PLASTIC, COATED'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, WOVEN PLASTIC, COATED AND LINER'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, WOVEN PLASTIC, WITH LINER'},
    {value:'', viewValue:'INTERMEDIATE BULK CONTAINER, WOVEN PLASTIC, WITHOUT COAT/LINER'},
    {value:'', viewValue:'IRON DRUM'},
    {value:'', viewValue:'JAR'},
    {value:'', viewValue:'JERRICAN (STEEL)'},
    {value:'', viewValue:'JERRICAN, CYLINDRICAL'},
    {value:'', viewValue:'JERRICAN, PLASTIC'},
    {value:'', viewValue:'JERRICAN, PLASTIC, NON-REMOVABLE HEAD'},
    {value:'', viewValue:'JERRICAN, PLASTIC, REMOVABLE HEAD'},
    {value:'', viewValue:'JERRICAN, RECTANGULAR'},
    {value:'', viewValue:'JERRICAN, STEEL, NON-REMOVABLE HEAD'},
    {value:'', viewValue:'JERRICAN, STEEL, REMOVABLE HEAD'},
    {value:'', viewValue:'JUG'},
    {value:'', viewValue:'JUTE BAG'},
    {value:'', viewValue:'KEG'},
    {value:'', viewValue:'LIFTVAN'},
    {value:'', viewValue:'LOG'},
    {value:'', viewValue:'LOGS, IN BUNDLE/BUNCH/TRUSS'},
    {value:'', viewValue:'LOT'},
    {value:'', viewValue:'MAT'},
    {value:'', viewValue:'MATCHBOX'},
    {value:'', viewValue:'METAL CASE, WITH PALLET BASE'},
    {value:'', viewValue:'METAL PACKAGE'},
    {value:'', viewValue:'MULTIPLE UNITS UNPACKED OR UNPACKAGED'},
    {value:'', viewValue:'MULTIPLY BAG'},
    {value:'', viewValue:'NEST'},
    {value:'', viewValue:'NET'},
    {value:'', viewValue:'NET, TUBE, PLASTIC'},
    {value:'', viewValue:'NET, TUBE, TEXTILE'},
    {value:'', viewValue:'PACKAGE, DISPLAY, CARDBOARD'},
    {value:'', viewValue:'PACKETS'},
    {value:'', viewValue:'PAIL'},
    {value:'', viewValue:'PALLET'},
    {value:'', viewValue:'PALLETS'},
    {value:'', viewValue:'PAPER BAG'},
    {value:'', viewValue:'PAPER BAG'},
    {value:'', viewValue:'PAPER WRAPPED PACKAGE'},
    {value:'', viewValue:'PARCEL'},
    {value:'', viewValue:'PEN'},
    {value:'', viewValue:'PIPE'},
    {value:'', viewValue:'PIPES, IN BUNDLE/BUNCH/TRUSS'},
    {value:'', viewValue:'PITCHER'},
    {value:'', viewValue:'PKGS'},
    {value:'', viewValue:'PLANK'},
    {value:'', viewValue:'PLANKS, IN BUNDLE/BUNCH/TRUSS'},
    {value:'', viewValue:'PLASTIC BAG'},
    {value:'', viewValue:'PLASTIC BOX'},
    {value:'', viewValue:'PLASTIC CASE, WITH PALLET BASE'},
    {value:'', viewValue:'PLASTIC CRATE'},
    {value:'', viewValue:'PLASTIC DRUM'},
    {value:'', viewValue:'PLASTIC PACKAGE'},
    {value:'', viewValue:'PLASTICS FILM BAG'},
    {value:'', viewValue:'PLATE'},
    {value:'', viewValue:'PLATES, IN BUNDLE/BUNCH/TRUSS'},
    {value:'', viewValue:'PLYWOOD DRUM'},
    {value:'', viewValue:'POLYSTYRENE TRAY'},
    {value:'', viewValue:'POT'},
    {value:'', viewValue:'POUCH'},
    {value:'', viewValue:'PUNNET'},
    {value:'', viewValue:'RACK'},
    {value:'', viewValue:'RACK, CLOTHING HANGER'},
    {value:'', viewValue:'RECEPTACLE, FIBRE'},
    {value:'', viewValue:'RECEPTACLE, METAL'},
    {value:'', viewValue:'RECEPTACLE, PAPER'},
    {value:'', viewValue:'RECEPTACLE, PLASTIC'},
    {value:'', viewValue:'RECEPTACLE, PLASTIC WRAPPED'},
    {value:'', viewValue:'RECEPTACLE, WOODEN'},
    {value:'', viewValue:'REDNET'},
    {value:'', viewValue:'REEL'},
    {value:'', viewValue:'RING'},
    {value:'', viewValue:'ROD'},
    {value:'', viewValue:'RODS'},
    {value:'', viewValue:'ROLL'},
    {value:'', viewValue:'SACHET'},
    {value:'', viewValue:'SACK'},
    {value:'', viewValue:'SACK, MULTI-WALL'},
    {value:'', viewValue:'SEA-CHEST'},
    {value:'', viewValue:'SET'},
    {value:'', viewValue:'SHEET'},
    {value:'', viewValue:'SHEET METAL'},
    {value:'', viewValue:'SHEET, PLASTIC WRAPPING'},
    {value:'', viewValue:'SHEETS, IN BUNDLE/BUNCH/TRUSS'},
    {value:'', viewValue:'SHRINKWRAPPED'},
    {value:'', viewValue:'SINGLE UNIT ,UNPACKED OR UNPACKAGED'},
    {value:'', viewValue:'SKID'},
    {value:'', viewValue:'SLAB'},
    {value:'', viewValue:'SLIPSHEET'},
    {value:'', viewValue:'SPINDLE'},
    {value:'', viewValue:'SPOOL'},
    {value:'', viewValue:'STEEL DRUM'},
    {value:'', viewValue:'STEEL DRUM, NON-REMOVABLE HEAD'},
    {value:'', viewValue:'STEEL DRUM, REMOVABLE HEAD'},
    {value:'', viewValue:'SUITCASE'},
    {value:'', viewValue:'TANK, CYLINDRICAL'},
    {value:'', viewValue:'TANK, RECTANGULAR'},
    {value:'', viewValue:'TEA-CHEST'},
    {value:'', viewValue:'TEXTILE BAG'},
    {value:'', viewValue:'TIERCE'},
    {value:'', viewValue:'TIN'},
    {value:'', viewValue:'TRAY'},
    {value:'', viewValue:'TRUNK'},
    {value:'', viewValue:'TRUSS'},
    {value:'', viewValue:'TUB'},
    {value:'', viewValue:'TUB, WITH LID'},
    {value:'', viewValue:'TUBE'},
    {value:'', viewValue:'TUBE, WITH NOZZLE'},
    {value:'', viewValue:'TUBES, IN BUNDLE/BUNCH/TRUSS'},
    {value:'', viewValue:'TUN'},
    {value:'', viewValue:'UNCAGED'},
    {value:'', viewValue:'UNPACKED OR UNPACKAGED'},
    {value:'', viewValue:'VACUUM-PACKED'},
    {value:'', viewValue:'VANPACK'},
    {value:'', viewValue:'VAT'},
    {value:'', viewValue:'VEHICLE'},
    {value:'', viewValue:'VIAL'},
    {value:'', viewValue:'WICKERBOTTLE'},
    {value:'', viewValue:'WOODEN PACKAGE'},
    {value:'', viewValue:'WOODEN BOX'},
    {value:'', viewValue:'WOODEN CASE, WITH PALLET BASE'},
    {value:'', viewValue:'WOODEN CRATE'},
    {value:'', viewValue:'WOODEN DRUM'},
    {value:'', viewValue:'WOODEN TRAY'},
    {value:'', viewValue:'WOVEN PLASTIC BAG'}];
  constructor() { }

  ngOnInit() {
  }

}
const ELEMENT_DATA: iCargoedit[] = [{
  container: '',
  package_goods: '',
  gw_vol: ''
}];